@startuml
title UC13 - Sơ đồ gói (Join phòng PUBLIC)
package "Flutter Client" {
  [UI]
  [RoomClient]
  [ApiService]
}
package "Server" {
  [RoomController]
  [RoomService]
}
package "Persistence" {
  [MySQL]
}
[UI] ..> [RoomClient]
[RoomClient] ..> [ApiService]
[ApiService] ..> [RoomController] : HTTP
[RoomController] ..> [RoomService]
[RoomService] ..> [MySQL] : JDBC
@enduml