@startuml
title UC17 - Sơ đồ gói (Tham gia cuộc gọi)
package "Flutter Client" {
  [Call UI]
  [WebSocketClient]
  [WebRTC Stack]
}
package "Server" {
  [SignalingEndpoint]
}
package "Peers" {
  [Client A]
  [Client B]
}
[Call UI] ..> [WebSocketClient]
[WebSocketClient] ..> [SignalingEndpoint] : WebSocket
[WebRTC Stack] ..> [WebSocketClient] : signaling
[Client A] ..> [WebRTC Stack]
[Client B] ..> [WebRTC Stack]
@enduml